theme: jekyll-theme-minimal
title: Keke Shang
paginate: 2
author: 尚可可
aubout: 南京大学
follow: 社交
indexContent: true
logo: https://github.com/KekeShang/kekeshang.github.io/blob/master/logo.png
copyright: 尚可可
